# index:
#    path: /
#    controller: App\Controller\DefaultController::homepage
# # the "app_lucky_number" route name is not important yet
# app_lucky_number:
#     path: /teste
#     controller: App\Controller\MainController::number